parameters:
    weed_php.master.address: "localhost:9333"

services:
    weed_php.transport:
        class: WeedPhp\Client
        arguments: [%weed_php.master.address%]
    weed_php.storage:
        class: Micjohnson\WeedPhpBundle\WeedStorage
        arguments: [@weed_php.transport]
    weed_php.manager:
        class: Micjohnson\WeedPhpBundle\WeedManager
        arguments: [@weed_php.storage]